let ShopifyMonitor = require('./base.js');
let monitors = [];
monitors.push(new ShopifyMonitor("https://deadstock.ca", 'DEADSTOCK'))
monitors.push(new ShopifyMonitor("https://size.ca", 'SIZECA'))
monitors.push(new ShopifyMonitor("https://jdsports.ca", 'JDSPORTSCA'))
monitors.push(new ShopifyMonitor("https://nrml.ca", 'NRML'))
monitors.push(new ShopifyMonitor("https://shop.havenshop.com", 'HAVEN'))
monitors.push(new ShopifyMonitor("https://capsuletoronto.com", 'CAPSULE'))
monitors.push(new ShopifyMonitor("https://nomadshop.net", 'NOMAD'))
monitors.push(new ShopifyMonitor("https://theclosetinc.com", 'CLOSETINC'))
monitors.push(new ShopifyMonitor("https://courtsidesneakers.com", 'COURTSIDE'))
monitors.push(new ShopifyMonitor("https://shop.exclucitylife.com", 'EXCLUCITY'))
monitors.push(new ShopifyMonitor("https://momentumshop.ca", 'MOMENTUM'))
monitors.push(new ShopifyMonitor("https://lessoneseven.com", 'LESSONESEVEN'))
monitors.push(new ShopifyMonitor("https://cncpts.com", 'CNCPTS'))
monitors.push(new ShopifyMonitor("https://gallery.canary---yellow.com", 'CANARYYELLOW'))
monitors.push(new ShopifyMonitor("https://hoopsheaven.com.au", 'NONE'))
monitors.push(new ShopifyMonitor("https://usgstore.com.au", 'NONE'))
monitors.push(new ShopifyMonitor("https://creme321.com", 'NONE'))
monitors.push(new ShopifyMonitor("https://leafproxies.com", 'NONE'))
monitors.push(new ShopifyMonitor("https://onenessboutique.com", 'NONE'))
monitors.push(new ShopifyMonitor("https://manorphx.com", 'NONE'))
monitors.push(new ShopifyMonitor("https://incu.com", 'NONE'))
monitors.push(new ShopifyMonitor("https://footzonenyc.com/", 'NONE'))
monitors.push(new ShopifyMonitor("https://fugitivetoys.com", 'NONE'))
monitors.push(new ShopifyMonitor("https://courtsidesneakers.com", 'NONE'))
monitors.push(new ShopifyMonitor("https://concrete.nl", 'NONE'))
monitors.push(new ShopifyMonitor("https://cncpts.ae", 'NONE'))
monitors.push(new ShopifyMonitor("https://chronotoys.com", 'NONE'))
monitors.push(new ShopifyMonitor("https://centre214.com", 'NONE'))
monitors.push(new ShopifyMonitor("https://ddtstore.com", 'NONE'))
for(let monitor of monitors) {
    monitor.monitor();
}